### ISSUE TITLE
Update w/ tags for Elixir 1.4.5 and 1.5.0

### ISSUE THREAD

**Issue by jamesvl** [aeons/docker-alpine#2]
Any chance we can get Dockerfiles defined for the latest versions of Elixir?

1.4.5 had further bug fixes for the 1.4.x releases, and I think is safe to do the exact same way as the 1.4.1 release.

1.5.0 is out no with a number of nice changes - I'm guessing Erlang 20 isn't an option until Alpine includes that in a new release, but 1.5.0 would still be nice as an option on Erlang 19.

**Comment by aeons** [comment]
I pushed images for Elixir 1.4.5 and 1.5.0. Both on Alpine 3.6 and Erlang 19.3.

Will take a look at Erlang 20 when the Alpine pkg is out.
