### ISSUE TITLE
Update to Alpine 3.7, Erlang 20.1, Elixir 1.6.1?

### ISSUE THREAD

**Issue by jamesvl** [aeons/docker-alpine#3]
I know, I may be the only person using this regularly enough to ask for these updates, but there are several that are possible now. Care to do your usual updates?

**Comment by aeons** [comment]
I just pushed the updates. I have mostly moved away from using these images.

Using multi-stage builds in docker makes all this mess go away :)

https://docs.docker.com/develop/develop-images/multistage-build/

**Comment by jamesvl** [comment]
Ah, I love the new multi-stage builds. I should convert these Docker jobs over to use them... thanks for updating, once again though!
